export const dbDefaults = {
    ID: "INTEGER PRIMARY KEY AUTOINCREMENT",
    title: "TEXT NOT NULL",
    slug: "VARCHAR(200) NOT NULL",
    created: "DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP",
    created_by: "INTEGER NOT NULL DEFAULT 0",
    updated: "DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP",
    updated_by: "INTEGER NOT NULL DEFAULT 0",
    status: "INTEGER NOT NULL DEFAULT 1",
    featured_id: "INTEGER NOT NULL DEFAULT 0"
  };
  